### ISSUE TITLE
Image scale

### ISSUE THREAD

**Issue by miketruax** [ToddAdelgren/ToddAdelgren.github.io#1]
When you hover over an image it currently moves the text around as well. If you were to use something like: 
``` css
  selector:hover{
  transform: scale(1.2);
}
```

it would increase the size of the image on hover without moving any other elements.
